// <auto-generated />
using System;
using MMatilde.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MMatilde.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717140644_AddBanners")]
    partial class AddBanners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_sync", "estado_sync", new[] { "pendiente", "en_proceso", "completado", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "rol_usuario", "rol_usuario", new[] { "admin", "viewer" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_precio", "tipo_precio", new[] { "markup_global", "markup_categoria", "descuento" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MMatilde.Api.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbreEnNuevaPestana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("abre_en_nueva_pestana");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_desde");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hasta");

                    b.Property<string>("ImagenDesktopUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("imagen_desktop_url");

                    b.Property<string>("ImagenMobileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("imagen_mobile_url");

                    b.Property<int?>("LinkCategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("link_categoria_id");

                    b.Property<int?>("LinkTagId")
                        .HasColumnType("integer")
                        .HasColumnName("link_tag_id");

                    b.Property<string>("LinkTipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Ninguno")
                        .HasColumnName("link_tipo");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("link_url");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("home")
                        .HasColumnName("ubicacion");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("LinkCategoriaId");

                    b.HasIndex("LinkTagId");

                    b.HasIndex("Ubicacion", "Orden");

                    b.ToTable("banners", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsMakor")
                        .HasColumnType("boolean");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Imagen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_hex");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("colores", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ConfiguracionSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("grupo");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion_sitio", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.IaConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contexto_json");

                    b.Property<string>("CorreccionEsperada")
                        .HasColumnType("text")
                        .HasColumnName("correccion_esperada");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Evaluacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("evaluacion");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("NotaCorreccion")
                        .HasColumnType("text")
                        .HasColumnName("nota_correccion");

                    b.Property<string>("ProductosJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("productos_json");

                    b.Property<string>("Proyecto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("proyecto");

                    b.Property<string>("ResultadoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resultado_json");

                    b.Property<DateTime?>("RevisadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_en");

                    b.Property<string>("Tecnica")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tecnica");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Evaluacion");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ia_consultas", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.IaEjemplo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Disparadores")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disparadores");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("RespuestaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("respuesta_json");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.ToTable("ia_ejemplos", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.IaReglaAprendida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int?>("ConsultaOrigenId")
                        .HasColumnType("integer")
                        .HasColumnName("consulta_origen_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Disparadores")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disparadores");

                    b.Property<string>("Regla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regla");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("ConsultaOrigenId");

                    b.ToTable("ia_reglas_aprendidas", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_default");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("medios_pago", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("activo");

                    b.Property<decimal?>("CantidadUnidadCompra")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_unidad_compra");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoMakor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_makor");

                    b.Property<decimal?>("ComisionTiendaPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("comision_tienda_porcentaje");

                    b.Property<string>("Composicion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("composicion");

                    b.Property<decimal?>("CostoMateriales")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo_materiales");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("DescripcionPublica")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_publica");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_porcentaje");

                    b.Property<bool>("Destacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("destacado");

                    b.Property<bool>("EsVentaLibre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_venta_libre");

                    b.Property<string>("EtiquetaUnidadCompra")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etiqueta_unidad_compra");

                    b.Property<string>("ImagenPublicaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("imagen_publica_url");

                    b.Property<decimal?>("IvaPorcentajeProducto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("iva_porcentaje_producto");

                    b.Property<decimal?>("ManoObra")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mano_obra");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<decimal?>("MargenElaboracionMonto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("margen_elaboracion_monto");

                    b.Property<decimal?>("MargenElaboracionPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen_elaboracion_porcentaje");

                    b.Property<decimal?>("MargenPorcentajeProducto")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen_porcentaje_producto");

                    b.Property<string>("ModoOrigenEconomico")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("REVENTA")
                        .HasColumnName("modo_origen_economico");

                    b.Property<string>("ModoPrecio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AUTOMATICO")
                        .HasColumnName("modo_precio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombrePublico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre_publico");

                    b.Property<decimal?>("PrecioMayorista")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_mayorista");

                    b.Property<decimal?>("PrecioMinorista")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_minorista");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("character varying(550)")
                        .HasColumnName("slug");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoria_id");

                    b.Property<string>("TitularConsignacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titular_consignacion");

                    b.Property<DateTime?>("UltimaSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_sync");

                    b.Property<string>("UnidadBase")
                        .HasColumnType("text")
                        .HasColumnName("unidad_base");

                    b.Property<bool>("UnidadCompraAutoDetectada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("unidad_compra_auto_detectada");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoMakor")
                        .IsUnique();

                    b.HasIndex("Destacado");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("alt_text");

                    b.Property<string>("CloudinaryPublicId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsDeProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_de_proveedor");

                    b.Property<bool>("EsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_principal");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("UrlOriginal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url_original");

                    b.Property<int?>("VarianteId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VarianteId");

                    b.ToTable("producto_imagenes", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoPresentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("CantidadUnidadBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("cantidad_unidad_base");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_default");

                    b.Property<decimal?>("MargenPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen_porcentaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("producto_presentaciones", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoRelacionado", b =>
                {
                    b.Property<int>("ProductoPrincipalId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_principal_id");

                    b.Property<int>("ProductoVinculadoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_vinculado_id");

                    b.HasKey("ProductoPrincipalId", "ProductoVinculadoId");

                    b.HasIndex("ProductoVinculadoId");

                    b.ToTable("producto_relacionados", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoTag", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("ProductoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("producto_tags", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoVariante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("activo");

                    b.Property<string>("CodigoArticulo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_articulo");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer")
                        .HasColumnName("color_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Medida")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medida");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("Talle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("talle");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductoId", "ColorId", "Talle", "Medida")
                        .IsUnique();

                    b.ToTable("producto_variantes", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("ScrapingConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("scraping_config");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UltimaSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_sync");

                    b.Property<string>("UrlBase")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_base");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.ReglaPrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<decimal>("MargenPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("margen_porcentaje");

                    b.Property<int?>("SubcategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("subcategoria_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("reglas_precio", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Subcategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsMakor")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Slug", "CategoriaId")
                        .IsUnique();

                    b.ToTable("subcategorias", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("categorias_json");

                    b.Property<string>("DetalleErrores")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_errores");

                    b.Property<int>("Errores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("errores");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FinalizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizado_en");

                    b.Property<DateTime>("IniciadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProductosActualizados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("productos_actualizados");

                    b.Property<int>("ProductosNuevos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("productos_nuevos");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer")
                        .HasColumnName("proveedor_id");

                    b.Property<string>("ResumenJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resumen_json");

                    b.Property<string>("TermsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("terms_json");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("VisibleEnCatalogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("visible_en_catalogo");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.TurnoVentaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeOnly>("HoraDesde")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_desde");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("turnos_venta", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("eliminado_en IS NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescuentoGlobalMonto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("descuento_global_monto");

                    b.Property<decimal>("DescuentoGlobalPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("descuento_global_porcentaje");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("GananciaNetaEstimada")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ganancia_neta_estimada");

                    b.Property<string>("MedioPagoSlug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("medio_pago");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<decimal>("SubtotalBruto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_bruto");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("turno");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuario_nombre");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("Turno");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.VentaCarritoBorrador", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UsuarioId");

                    b.ToTable("venta_carritos_borrador", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.VentaLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("ComisionTiendaPorcentajeSnapshot")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("comision_tienda_porcentaje_snapshot");

                    b.Property<decimal?>("CostoCompraSnapshot")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo_compra_snapshot");

                    b.Property<decimal?>("CostoMaterialesSnapshot")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costo_materiales_snapshot");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescuentoGlobalAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("descuento_global_asignado");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("descuento_monto");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<decimal>("GananciaNetaEstimada")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ganancia_neta_estimada");

                    b.Property<decimal?>("ManoObraSnapshot")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mano_obra_snapshot");

                    b.Property<string>("ModoOrigenEconomico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modo_origen_economico");

                    b.Property<string>("NotaLinea")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nota_linea");

                    b.Property<decimal>("PrecioUnitarioVenta")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario_venta");

                    b.Property<int?>("PresentacionId")
                        .HasColumnType("integer")
                        .HasColumnName("presentacion_id");

                    b.Property<string>("PresentacionNombre")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("presentacion_nombre");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("producto_nombre");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("SubtotalBruto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_bruto");

                    b.Property<int?>("VarianteId")
                        .HasColumnType("integer")
                        .HasColumnName("variante_id");

                    b.Property<string>("VarianteLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("variante_label");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("venta_lineas", (string)null);
                });

            modelBuilder.Entity("MMatilde.Api.Models.Banner", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Categoria", "LinkCategoria")
                        .WithMany()
                        .HasForeignKey("LinkCategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMatilde.Api.Models.Tag", "LinkTag")
                        .WithMany()
                        .HasForeignKey("LinkTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkCategoria");

                    b.Navigation("LinkTag");
                });

            modelBuilder.Entity("MMatilde.Api.Models.IaReglaAprendida", b =>
                {
                    b.HasOne("MMatilde.Api.Models.IaConsulta", "ConsultaOrigen")
                        .WithMany()
                        .HasForeignKey("ConsultaOrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConsultaOrigen");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Producto", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MMatilde.Api.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MMatilde.Api.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MMatilde.Api.Models.Subcategoria", "Subcategoria")
                        .WithMany("Productos")
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoImagen", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMatilde.Api.Models.ProductoVariante", "Variante")
                        .WithMany("Imagenes")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Producto");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoPresentacion", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Producto", "Producto")
                        .WithMany("Presentaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoRelacionado", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Producto", "ProductoPrincipal")
                        .WithMany("Relacionados")
                        .HasForeignKey("ProductoPrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMatilde.Api.Models.Producto", "ProductoVinculado")
                        .WithMany()
                        .HasForeignKey("ProductoVinculadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductoPrincipal");

                    b.Navigation("ProductoVinculado");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoTag", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Producto", "Producto")
                        .WithMany("Tags")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMatilde.Api.Models.Tag", "Tag")
                        .WithMany("Productos")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoVariante", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MMatilde.Api.Models.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Subcategoria", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Categoria", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MMatilde.Api.Models.SyncLog", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Proveedor", "Proveedor")
                        .WithMany("SyncLogs")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Venta", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MMatilde.Api.Models.VentaCarritoBorrador", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MMatilde.Api.Models.VentaLinea", b =>
                {
                    b.HasOne("MMatilde.Api.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MMatilde.Api.Models.Venta", "Venta")
                        .WithMany("Lineas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Producto", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Presentaciones");

                    b.Navigation("Relacionados");

                    b.Navigation("Tags");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("MMatilde.Api.Models.ProductoVariante", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Subcategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Tag", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("MMatilde.Api.Models.Venta", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
