name: Deploy .NET 8 Backend to VPS (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno de despliegue'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore MMatilde.Api/MMatilde.Api.csproj

      - name: Publish Application
        run: |
          dotnet publish MMatilde.Api/MMatilde.Api.csproj -c Release -o ./publish --no-restore

      - name: Stop IIS Application Pool
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "MerceriaBack"

      - name: Clean IIS folder
        run: |
          Remove-Item "C:\inetpub\wwwroot\MerceriaBack\*" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Deploy to IIS
        run: |
          Copy-Item -Path "./publish/*" -Destination "C:\inetpub\wwwroot\MerceriaBack" -Recurse -Force

      - name: Start IIS Application Pool
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "MerceriaBack"
